# Generated by Django 3.2.9 on 2023-12-09 15:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('objectives', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectives',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='objectives',
            name='end_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='objectives',
            name='start_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
