# Generated by Django 3.2.9 on 2023-12-10 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objectives', '0002_auto_20231209_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectives',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='objectives',
            name='start_date',
            field=models.DateField(),
        ),
    ]
